import torch

b = torch.rand(32)
b = b.unsqueeze(1).unsqueeze(2).unsqueeze(0)
# torch.Size([1, 32, 1, 1])
print(b.shape)
# torch.Size([32])
print(b.squeeze().shape)
# torch.Size([32, 1, 1])
print(b.squeeze(0).shape)
# torch.Size([1, 32, 1])
print(b.squeeze(-1).shape)
# torch.Size([1, 32, 1, 1])
print(b.squeeze(1).shape)
# torch.Size([1, 32, 1])
print(b.squeeze(2).shape)
# torch.Size([1, 32, 1])
print(b.squeeze(3).shape)
# torch.Size([32, 1, 1])
print(b.squeeze(-4).shape)